import { Channel, Category } from './types';

export const CATEGORIES: Category[] = [
  { id: 'all', name: 'Todos', icon: 'LayoutGrid' },
  { id: 'futebol', name: 'Futebol', icon: 'Trophy' },
  { id: 'nba', name: 'NBA', icon: 'Dribbble' },
  { id: 'lutas', name: 'Lutas', icon: 'Sword' },
  { id: 'filmes', name: 'Filmes', icon: 'Film' },
  { id: 'series', name: 'Séries', icon: 'Tv' },
];

export const CHANNELS: Channel[] = [
  // --- PLATAFORMAS OFICIAIS GRATUITAS / REDES ---
  {
    id: 'caze-tv',
    name: 'CazéTV (YouTube)',
    description: 'Jogos ao vivo e gratuitos com o Casimiro',
    logo: 'https://ui-avatars.com/api/?name=Caze&background=FFD700&color=000',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.youtube.com/@CazeTV',
    category: 'futebol',
  },
  {
    id: 'espn-br',
    name: 'ESPN Brasil',
    description: 'Notícias e destaques oficiais',
    logo: 'https://logo.clearbit.com/espn.com.br',
    thumbnail: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.youtube.com/@espnbrasil',
    category: 'futebol',
  },
  {
    id: 'tnt-sports-br',
    name: 'TNT Sports BR',
    description: 'O melhor da Champions no YouTube',
    logo: 'https://logo.clearbit.com/tntsports.com.br',
    thumbnail: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.youtube.com/@TNTSportsBR',
    category: 'futebol',
  },
  {
    id: 'nba-brasil',
    name: 'NBA Brasil Official',
    description: 'Basquete Americano com sotaque brazuca',
    logo: 'https://logo.clearbit.com/nba.com',
    thumbnail: 'https://images.unsplash.com/photo-1504450758481-7338eba7524a?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.youtube.com/@nbabrasil',
    category: 'nba',
  },
  {
    id: 'dazn-premium',
    name: 'DAZN Sports',
    description: 'Plataforma oficial de lives esportivas',
    logo: 'https://logo.clearbit.com/dazn.com',
    thumbnail: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.dazn.com/pt-BR/sport/Sport:289u5typ3vp4ifwh5thalohmq',
    category: 'futebol',
  },

  // --- TRANSMISSÕES DIRETAS (HUB PREMIUM) ---
  {
    id: 'hub-fawa',
    name: 'Fawa News Live',
    description: 'Futebol, NBA, Lutas e mais',
    logo: 'https://ui-avatars.com/api/?name=FN&background=39FF14&color=000',
    thumbnail: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://livee.mov/fawa-news.live/',
    category: 'futebol',
  },
  {
    id: 'hub-hesgoal',
    name: 'Hesgoal Original',
    description: 'Foco total em Futebol Europeu e Mundial',
    logo: 'https://logo.clearbit.com/hesgoal.football',
    url: 'https://hesgoal.football/',
    category: 'futebol',
  },
  {
    id: 'hub-arena',
    name: 'Arena Digital 24h',
    description: 'O melhor do Esporte, Lutas e Entretenimento',
    logo: 'https://ui-avatars.com/api/?name=AD&background=000&color=fff',
    url: 'https://000007.mov/watch.html?id=9062&s=0',
    category: 'futebol',
  },

  // --- TRANSMISSÕES NBA (HUB) ---
  {
    id: 'hub-fawa-nba',
    name: 'Fawa News (NBA)',
    description: 'Transmissão completa de Basquete',
    logo: 'https://ui-avatars.com/api/?name=NBA&background=39FF14&color=000',
    url: 'https://livee.mov/fawa-news.live/',
    category: 'nba',
  },
  {
    id: 'hub-arena-nba',
    name: 'Arena Digital (Basquete)',
    description: 'NBA e Ligas Internacionais',
    logo: 'https://ui-avatars.com/api/?name=AD&background=000&color=fff',
    url: 'https://000007.mov/watch.html?id=9062&s=0',
    category: 'nba',
  },

  // --- TRANSMISSÕES LUTAS (HUB) ---
  {
    id: 'hub-fawa-lutas',
    name: 'Fawa News (Lutas)',
    description: 'UFC, Boxe e MMA ao vivo',
    logo: 'https://ui-avatars.com/api/?name=UC&background=39FF14&color=000',
    url: 'https://livee.mov/fawa-news.live/',
    category: 'lutas',
  },
  {
    id: 'hub-arena-lutas',
    name: 'Arena Digital (UFC)',
    description: 'Eventos de Luta e Combates',
    logo: 'https://ui-avatars.com/api/?name=COMB&background=000&color=fff',
    url: 'https://000007.mov/watch.html?id=9062&s=0',
    category: 'lutas',
  },

  // --- FUTEBOL (SÉRIE A / TIMES / LIGAS) ---
  {
    id: 'bra-flamengo',
    name: 'Flamengo',
    description: 'Jogos do Mengão ao vivo',
    logo: 'https://logo.clearbit.com/flamengo.com.br',
    thumbnail: 'https://images.unsplash.com/photo-1574629810360-7efbbe195018?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.futebolgratuito.net/search/label/Flamengo?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-corinthians',
    name: 'Corinthians',
    description: 'Jogos do Timão ao vivo',
    logo: 'https://logo.clearbit.com/corinthians.com.br',
    thumbnail: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.futebolgratuito.net/search/label/Corinthians?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-palmeiras',
    name: 'Palmeiras',
    description: 'Jogos do Verdão ao vivo',
    logo: 'https://logo.clearbit.com/palmeiras.com.br',
    thumbnail: 'https://images.unsplash.com/photo-1517466788219-b803bb915c39?auto=format&fit=crop&q=80&w=800',
    status: 'live',
    url: 'https://www.futebolgratuito.net/search/label/Palmeiras?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-sao-paulo',
    name: 'São Paulo',
    description: 'Jogos do Tricolor ao vivo',
    logo: 'https://logo.clearbit.com/saopaulofc.net',
    url: 'https://www.futebolgratuito.net/search/label/Sao-Paulo?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-brasileirao',
    name: 'Brasileirão',
    description: 'Série A e Série B',
    logo: 'https://logo.clearbit.com/cbf.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Brasileir%C3%A3o?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-copa-brasil',
    name: 'Copa do Brasil',
    description: 'O mata-mata mais desejado',
    logo: 'https://logo.clearbit.com/cbf.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Copa%20do%20Brasil?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-champions',
    name: 'Champions League',
    description: 'A maior liga do mundo',
    logo: 'https://logo.clearbit.com/uefa.com',
    url: 'https://www.futebolgratuito.net/search/label/Champions%20League?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-barcelona',
    name: 'Barcelona',
    description: 'Jogos do Barça ao vivo',
    logo: 'https://logo.clearbit.com/fcbarcelona.com',
    url: 'https://www.futebolgratuito.net/search/label/Barcelona?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-real-madrid',
    name: 'Real Madrid',
    description: 'Jogos dos Merengues',
    logo: 'https://logo.clearbit.com/realmadrid.com',
    url: 'https://www.futebolgratuito.net/search/label/Real%20Madrid?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'saudi-al-nassr',
    name: 'Al-Nassr',
    description: 'Jogos de Cristiano Ronaldo',
    logo: 'https://logo.clearbit.com/alnassr.sa',
    url: 'https://www.futebolgratuito.net/search/label/Al-Nassr?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-atletico-mg',
    name: 'Atlético-MG',
    description: 'Jogos do Galo ao vivo',
    logo: 'https://logo.clearbit.com/atletico.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Atl%C3%A9tico-MG?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-gremio',
    name: 'Grêmio',
    description: 'Jogos do Imortal ao vivo',
    logo: 'https://logo.clearbit.com/gremio.net',
    url: 'https://www.futebolgratuito.net/search/label/Gr%C3%AAmio?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-internacional',
    name: 'Internacional',
    description: 'Jogos do Colorado ao vivo',
    logo: 'https://logo.clearbit.com/internacional.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Internacional?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-fluminense',
    name: 'Fluminense',
    description: 'Jogos do Tricolor das Laranjeiras',
    logo: 'https://logo.clearbit.com/fluminense.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Fluminense?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-bahia',
    name: 'Bahia',
    description: 'Jogos do Esquadrão de Aço',
    logo: 'https://logo.clearbit.com/esporteclubebahia.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Bahia?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-premier-league',
    name: 'Inglês (Premier League)',
    description: 'O melhor futebol da Europa',
    logo: 'https://logo.clearbit.com/premierleague.com',
    url: 'https://www.futebolgratuito.net/search/label/Ingl%C3%AAs?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-argentino',
    name: 'Argentino',
    description: 'Campeonato Argentino ao vivo',
    logo: 'https://logo.clearbit.com/afa.org.ar',
    url: 'https://www.futebolgratuito.net/search/label/Argentino?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-argentina-selecao',
    name: 'Seleção Argentina',
    description: 'Jogos da Albiceleste',
    logo: 'https://logo.clearbit.com/afa.org.ar',
    url: 'https://www.futebolgratuito.net/search/label/Argentina?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-amistosos',
    name: 'Amistosos',
    description: 'Jogos Preparatórios',
    logo: 'https://logo.clearbit.com/cbf.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Amistosos?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-america-mg',
    name: 'América-MG',
    description: 'Jogos do Coelho',
    logo: 'https://logo.clearbit.com/americamineiro.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Am%C3%A9rica-MG?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-amazonas',
    name: 'Amazonas FC',
    description: 'A Onça Pintada ao vivo',
    logo: 'https://ui-avatars.com/api/?name=AM&background=000&color=fff',
    url: 'https://www.futebolgratuito.net/search/label/Amazonas?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-alemao',
    name: 'Alemão (Bundesliga)',
    description: 'Futebol germânico ao vivo',
    logo: 'https://logo.clearbit.com/bundesliga.com',
    url: 'https://www.futebolgratuito.net/search/label/Alem%C3%A3o?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'saudi-al-ittihad',
    name: 'Al-Ittihad',
    description: 'Jogos de Benzema',
    logo: 'https://logo.clearbit.com/alittihad.sa',
    url: 'https://www.futebolgratuito.net/search/label/Al-Ittihad?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'saudi-al-hilal',
    name: 'Al-Hilal',
    description: 'Jogos de Neymar Jr',
    logo: 'https://logo.clearbit.com/alhilal.com',
    url: 'https://www.futebolgratuito.net/search/label/Al-Hilal?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-agenda',
    name: 'Agenda de Jogos',
    description: 'Veja o que passa hoje',
    logo: 'https://ui-avatars.com/api/?name=AJ&background=39FF14&color=000',
    url: 'https://www.futebolgratuito.net/search/label/Agenda?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-benfica',
    name: 'Benfica',
    description: 'As Águias de Portugal',
    logo: 'https://logo.clearbit.com/slbenfica.pt',
    url: 'https://www.futebolgratuito.net/search/label/Benfica?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-bayern',
    name: 'Bayern de Munique',
    description: 'O gigante da Baviera',
    logo: 'https://logo.clearbit.com/fcbayern.com',
    url: 'https://www.futebolgratuito.net/search/label/Bayern%20De%20Munique?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-avai',
    name: 'Avaí',
    description: 'O Leão da Ilha',
    logo: 'https://logo.clearbit.com/avai.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Ava%C3%AD?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-atletico-go',
    name: 'Atlético-GO',
    description: 'O Dragão ao vivo',
    logo: 'https://logo.clearbit.com/atleticogoianiense.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Atl%C3%A9tico-GO?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-atletico-madrid',
    name: 'Atlético de Madrid',
    description: 'Os Colchoneros ao vivo',
    logo: 'https://logo.clearbit.com/atleticodemadrid.com',
    url: 'https://www.futebolgratuito.net/search/label/Atl%C3%A9tico%20de%20Madrid?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-athletico-pr',
    name: 'Athletico-PR',
    description: 'O Furacão ao vivo',
    logo: 'https://logo.clearbit.com/athletico.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Athletico-PR?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-arsenal',
    name: 'Arsenal',
    description: 'Os Gunners ao vivo',
    logo: 'https://logo.clearbit.com/arsenal.com',
    url: 'https://www.futebolgratuito.net/search/label/Arsenal?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-copa-mundo',
    name: 'Copa do Mundo',
    description: 'O maior espetáculo da terra',
    logo: 'https://logo.clearbit.com/fifa.com',
    url: 'https://www.futebolgratuito.net/search/label/Copa%20do%20Mundo?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-copa-america',
    name: 'Copa América',
    description: 'O orgulho sul-americano',
    logo: 'https://logo.clearbit.com/conmebol.com',
    url: 'https://www.futebolgratuito.net/search/label/Copa%20Am%C3%A9rica?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-chelsea',
    name: 'Chelsea',
    description: 'The Blues ao vivo',
    logo: 'https://logo.clearbit.com/chelseafc.com',
    url: 'https://www.futebolgratuito.net/search/label/Chelsea?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-chapecoense',
    name: 'Chapecoense',
    description: 'O Verdão do Oeste ao vivo',
    logo: 'https://logo.clearbit.com/chapecoense.com',
    url: 'https://www.futebolgratuito.net/search/label/Chapecoense?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-ceara',
    name: 'Ceará',
    description: 'O Vozão ao vivo',
    logo: 'https://logo.clearbit.com/cearasc.com',
    url: 'https://www.futebolgratuito.net/search/label/Cear%C3%A1?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-bragantino',
    name: 'Bragantino',
    description: 'Massa Bruta ao vivo',
    logo: 'https://logo.clearbit.com/redbullbragantino.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Bragantino?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-botafogo-sp',
    name: 'Botafogo-SP',
    description: 'Pantera ao vivo',
    logo: 'https://logo.clearbit.com/botafogofutebolsa.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Botafogo-SP?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-boca-juniors',
    name: 'Boca Juniors',
    description: 'Xeneizes ao vivo',
    logo: 'https://logo.clearbit.com/bocajuniors.com.ar',
    url: 'https://www.futebolgratuito.net/search/label/Boca%20Juniors?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-europa-league',
    name: 'Europa League',
    description: 'A segunda maior da Europa',
    logo: 'https://logo.clearbit.com/uefa.com',
    url: 'https://www.futebolgratuito.net/search/label/Europa%20League?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-estaduais',
    name: 'Estaduais',
    description: 'Campeonatos Regionais',
    logo: 'https://logo.clearbit.com/cbf.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Estaduais?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-eliminatorias',
    name: 'Eliminatórias',
    description: 'Rumo à Copa do Mundo',
    logo: 'https://logo.clearbit.com/fifa.com',
    url: 'https://www.futebolgratuito.net/search/label/Eliminat%C3%B3rias?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-fortaleza',
    name: 'Fortaleza',
    description: 'Leão do Pici ao vivo',
    logo: 'https://logo.clearbit.com/fortalezaec.net',
    url: 'https://www.futebolgratuito.net/search/label/Fortaleza?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-frances',
    name: 'Francês (Ligue 1)',
    description: 'Fogo em campo na França',
    logo: 'https://logo.clearbit.com/ligue1.com',
    url: 'https://www.futebolgratuito.net/search/label/Franc%C3%AAs?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-feminino',
    name: 'Futebol Feminino',
    description: 'As craques em campo',
    logo: 'https://logo.clearbit.com/cbf.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Futebol%20Feminino?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-goias',
    name: 'Goiás',
    description: 'Esmeraldino ao vivo',
    logo: 'https://logo.clearbit.com/goiasec.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Goi%C3%A1s?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-inter-milao',
    name: 'Inter de Milão',
    description: 'Nerazzurri ao vivo',
    logo: 'https://logo.clearbit.com/inter.it',
    url: 'https://www.futebolgratuito.net/search/label/Inter%20de%20Mil%C3%A3o?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-nordeste',
    name: 'Copa do Nordeste',
    description: 'Lampions League',
    logo: 'https://ui-avatars.com/api/?name=CN&background=000&color=fff',
    url: 'https://www.futebolgratuito.net/search/label/Copa%20do%20Nordeste?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-coritiba',
    name: 'Coritiba',
    description: 'Coxa Branca ao vivo',
    logo: 'https://logo.clearbit.com/coritiba.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Coritiba?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-crb',
    name: 'CRB',
    description: 'Galo de Campina ao vivo',
    logo: 'https://logo.clearbit.com/crb-al.com.br',
    url: 'https://www.futebolgratuito.net/search/label/CRB?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-criciuma',
    name: 'Criciúma',
    description: 'Tigrão ao vivo',
    logo: 'https://logo.clearbit.com/criciuma.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Crici%C3%BAma?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'bra-cuiaba',
    name: 'Cuiabá',
    description: 'Dourado ao vivo',
    logo: 'https://logo.clearbit.com/cuiabaesporteclube.com.br',
    url: 'https://www.futebolgratuito.net/search/label/Cuiab%C3%A1?&max-results=6',
    category: 'futebol',
  },
  {
    id: 'int-nba-pass',
    name: 'NBA League Pass',
    description: 'Basquete Americano ao vivo',
    logo: 'https://logo.clearbit.com/nba.com',
    url: '#',
    category: 'nba',
  },
  {
    id: 'ufc-pass',
    name: 'UFC Fight Pass',
    description: 'MMA e Artes Marciais',
    logo: 'https://logo.clearbit.com/ufc.com',
    thumbnail: 'https://images.unsplash.com/photo-1555597673-b21d5c935865?auto=format&fit=crop&q=80&w=800',
    status: 'online',
    url: '#',
    category: 'lutas',
  },
  {
    id: 'telegram-movies',
    name: 'Telegram Filmes HD',
    description: 'Catálogo completo via Telegram',
    logo: 'https://logo.clearbit.com/telegram.org',
    url: 'https://t.me/FilmesOnline_HD',
    category: 'filmes',
  },
  {
    id: 'hbo-max',
    name: 'HBO Max',
    description: 'Filmes e Séries Premium',
    logo: 'https://logo.clearbit.com/hbomax.com',
    thumbnail: 'https://images.unsplash.com/photo-1485846234645-a62644f84728?auto=format&fit=crop&q=80&w=800',
    status: 'online',
    url: '#',
    category: 'filmes',
    subChannels: [
      { id: 'hbo-tg-1', name: 'Canal Telegram 1 (Séries)', url: 'https://t.me/SériesOnline_HD', type: 'telegram' },
      { id: 'hbo-web-1', name: 'Plataforma Web (Backup)', url: 'https://000007.mov/', type: 'website' }
    ]
  },
  {
    id: 'netflix-cat',
    name: 'Netflix',
    description: 'Originais e Filmes',
    logo: 'https://logo.clearbit.com/netflix.com',
    thumbnail: 'https://images.unsplash.com/photo-1594909122845-11baa439b7bf?auto=format&fit=crop&q=80&w=800',
    status: 'online',
    url: '#',
    category: 'series',
    subChannels: [
      { id: 'net-tg-1', name: 'Canal Telegram 1 (Filmes)', url: 'https://t.me/FilmesOnline_HD', type: 'telegram' },
      { id: 'net-bw', name: 'Canal 2 (Web Movies)', url: 'https://web.bluewirelight.net/', type: 'website' },
      { id: 'net-tg-3', name: 'Canal 3 (TeleGrupos)', url: 'https://telegrupos.com.br/filmes-e-sries-premium-2/', type: 'website' },
      { id: 'net-web-1', name: 'Assistir Online (Opção 1)', url: 'https://livee.mov/', type: 'website' }
    ]
  },
  {
    id: 'maisfut-tg',
    name: 'Canal Mais Fut',
    description: 'Futebol ao vivo no Telegram',
    logo: 'https://logo.clearbit.com/telegram.org',
    url: 'https://t.me/canalmaisfut',
    category: 'futebol',
  },
  {
    id: 'bluewire-movies',
    name: 'Bluewire Movies',
    description: 'Catálogo de Filmes e Séries Online',
    logo: 'https://ui-avatars.com/api/?name=BW&background=000&color=fff',
    url: 'https://web.bluewirelight.net/',
    category: 'filmes',
  },
  {
    id: 'telegrupos-premium',
    name: 'TeleGrupos Premium',
    description: 'Comunidade de Filmes e Séries',
    logo: 'https://ui-avatars.com/api/?name=TG&background=000&color=fff',
    url: 'https://telegrupos.com.br/filmes-e-sries-premium-2/',
    category: 'series',
  },
];
